
import os, zipfile, datetime
from state import ProjectState
from config import OUTPUT_DIR

REPORT_DIR = os.path.join(OUTPUT_DIR, "Report")
CODE_DIR   = os.path.join(OUTPUT_DIR, "Code")


def _write(path: str, content: str):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    rel = os.path.relpath(path, OUTPUT_DIR)
    print(f"║  → {rel}")


def _readme(state: ProjectState) -> str:
    now    = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    tasks  = "\n".join(f"- [x] {t}" for t in state.get("tasks", []))
    charts = "\n".join(f"  - Charts/{os.path.basename(p)}"
                       for p in state.get("chart_paths", []))
    images = "\n".join(f"  - Images/{os.path.basename(p)}"
                       for p in state.get("image_paths", []))
    videos = "\n".join(f"  - [{v['title']}]({v['url']})"
                       for v in state.get("video_links", []))
    refs   = "\n".join(f"  {r}" for r in state.get("references", []))

    sections = []
    if charts:  sections.append(f"## 📊 Charts\n{charts}")
    if images:  sections.append(f"## 🖼️ Images (via Playwright)\n{images}")
    if videos:  sections.append(f"## 🎬 Videos (YouTube)\n{videos}")
    if state.get("timeline"):
        tl = "\n".join(f"  - **{e['year']}** — {e['event']}"
                       for e in state["timeline"][:6])
        sections.append(f"## ⏳ Timeline (preview)\n{tl}")
    if state.get("quiz"):
        sections.append(f"## 🧪 Quiz\n  See `Report/quiz.txt` for 5 MCQ questions")
    if state.get("mindmap"):
        sections.append(f"## 🧠 Mind Map\n  See `Report/mindmap.txt`")
    if state.get("code","").strip():
        sections.append(f"## 👨‍💻 Code\n  See `Code/main.py`")
    if state.get("pdf_path"):
        sections.append(f"## 📄 PDF Report\n  See `Report/project_report.pdf`")
    if refs:
        sections.append(f"## 📚 References\n{refs}")

    return f"""# 📚 {state['topic']}

> **Auto-generated by Smart Agentic Project System**
> Model: `gpt-4o-mini` · Orchestrator: LangGraph · {now}

---

## 📋 Tasks
{tasks}

## 📁 Files
- `Report/report.txt`          — Full academic report
- `Report/research_notes.txt`  — Deep research notes
- `Report/quiz.txt`            — Revision quiz
- `Report/timeline.txt`        — Historical timeline
- `Report/mindmap.txt`         — Concept mind map
- `Report/tables.txt`          — Data comparison tables
- `Report/project_report.pdf`  — Full PDF report
- `Code/main.py`               — Python implementation

---

{"---".join(chr(10)+s+chr(10) for s in sections)}

---
*Generated by Smart Agentic Project System*
"""


def file_node(state: ProjectState) -> ProjectState:
    print("\n  FILE AGENT ════════════════════════════════════╗")

    errors = list(state.get("errors", []))

    # Report
    try:
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        _write(os.path.join(REPORT_DIR, "report.txt"),
               f"PROJECT REPORT\n{'='*60}\n"
               f"Topic : {state['topic']}\nDate  : {now}\n{'='*60}\n\n"
               + state.get("theory", ""))
    except Exception as e:
        errors.append(f"report.txt: {e}")

    # Research notes
    try:
        refs = "\n\nREFERENCES\n" + "\n".join(state.get("references", []))
        _write(os.path.join(REPORT_DIR, "research_notes.txt"),
               f"RESEARCH NOTES — {state['topic']}\n{'='*60}\n\n"
               + state.get("research_notes", "") + refs)
    except Exception as e:
        errors.append(f"research_notes.txt: {e}")

    # Code
    try:
        code = state.get("code", "").strip()
        if code:
            _write(os.path.join(CODE_DIR, "main.py"),
                   f'"""\nProject: {state["topic"]}\nAuto-generated\n"""\n\n' + code)
    except Exception as e:
        errors.append(f"main.py: {e}")

    # README
    try:
        _write(os.path.join(OUTPUT_DIR, "README.md"), _readme(state))
    except Exception as e:
        errors.append(f"README.md: {e}")

    # ZIP
    zip_path = ""
    try:
        ts       = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        zip_path = os.path.join(os.path.dirname(OUTPUT_DIR), f"project_{ts}.zip")
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for root, _, files in os.walk(OUTPUT_DIR):
                for fn in files:
                    ap  = os.path.join(root, fn)
                    arc = os.path.relpath(ap, os.path.dirname(OUTPUT_DIR))
                    zf.write(ap, arc)
        size = os.path.getsize(zip_path) // 1024
        print(f"║  → ZIP: project_{ts}.zip  ({size} KB)")
    except Exception as e:
        errors.append(f"ZIP: {e}")

    print("╚══════════════════════════════════════════════════════╝")
    return {**state, "zip_path": zip_path, "current_step": "done",
            "errors": errors,
            "messages": state["messages"] + [
                {"role": "file_agent", "content": "project packaged"}]}
